// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsO34ASPQwYwnKkowGdxBOtGMVXSfN7Vc',
    appId: '1:335524830268:web:4b84f471f1a22d5840f739',
    messagingSenderId: '335524830268',
    projectId: 'citric-plexus-190723',
    authDomain: 'citric-plexus-190723.firebaseapp.com',
    databaseURL: 'https://citric-plexus-190723.firebaseio.com',
    storageBucket: 'citric-plexus-190723.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHzs6Sluq7JxbP-iQk962GuZLnSkuVYyI',
    appId: '1:335524830268:android:60ab050f0d82629140f739',
    messagingSenderId: '335524830268',
    projectId: 'citric-plexus-190723',
    databaseURL: 'https://citric-plexus-190723.firebaseio.com',
    storageBucket: 'citric-plexus-190723.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHceUbXFHhGRsppS9Bu6lioM_0pcWtp0o',
    appId: '1:335524830268:ios:01c3ca02a452d77c40f739',
    messagingSenderId: '335524830268',
    projectId: 'citric-plexus-190723',
    databaseURL: 'https://citric-plexus-190723.firebaseio.com',
    storageBucket: 'citric-plexus-190723.appspot.com',
    androidClientId: '335524830268-0n9endfhp0v60pgjoovnd532jnv8vpde.apps.googleusercontent.com',
    iosClientId: '335524830268-e1rhanbhis04ft6h76qdjavalitdrso2.apps.googleusercontent.com',
    iosBundleId: 'com.example.halifaxline',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHceUbXFHhGRsppS9Bu6lioM_0pcWtp0o',
    appId: '1:335524830268:ios:01c3ca02a452d77c40f739',
    messagingSenderId: '335524830268',
    projectId: 'citric-plexus-190723',
    databaseURL: 'https://citric-plexus-190723.firebaseio.com',
    storageBucket: 'citric-plexus-190723.appspot.com',
    androidClientId: '335524830268-0n9endfhp0v60pgjoovnd532jnv8vpde.apps.googleusercontent.com',
    iosClientId: '335524830268-e1rhanbhis04ft6h76qdjavalitdrso2.apps.googleusercontent.com',
    iosBundleId: 'com.example.halifaxline',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFbOODZnkAWoaFYKUw-OrbOc19UBhmGCA',
    appId: '1:335524830268:web:4c806db68afb39d540f739',
    messagingSenderId: '335524830268',
    projectId: 'citric-plexus-190723',
    authDomain: 'citric-plexus-190723.firebaseapp.com',
    databaseURL: 'https://citric-plexus-190723.firebaseio.com',
    storageBucket: 'citric-plexus-190723.appspot.com',
  );
}
